# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg|.*\.patch)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^python/cucim/src/.*
        args: ["--settings-path=python/cucim/pyproject.toml"]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: (python|legate)/.*
        args: ["--config", "python/cucim/pyproject.toml"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        files: python/.*$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: ["--toml", "python/cucim/pyproject.toml"]
        additional_dependencies:
          - tomli
