# Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
# See file LICENSE for terms.

[tool.isort]
force_single_line = false
line_length = 80
forced_separate = "test_cucim"
force_grid_wrap = 0
multi_line_output = 3
order_by_type = true
combine_as_imports = true
include_trailing_comma = true
known_first_party = [
    "cucim",
]
default_section = "THIRDPARTY"
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
skip = [
    "3rdparty",
    "thirdparty",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "ci",
    "cpp",
    "_build",
    "build",
    "build-debug",
    "build-release",
    "_deps",
    "dist",
]

[tool.pytest.ini_options]
# If a pytest section is found in one of the possible config files
# (pytest.ini, tox.ini or setup.cfg), then pytest will not look for any others,
# so if you add a pytest config section elsewhere,
# you will need to delete this section from setup.cfg.
norecursedirs = "migrations"
python_files = [
    "test_*.py",
    "*_test.py",
    "tests.py",
]
addopts = [
    "-ra",
    "--strict-markers",
    # --doctest-modules",
    # --doctest-glob=\*.rst",
    "--tb=short",
    "--ignore-glob=build*",
]
testpaths = [
    "src",
    "tests",
]

[tool.ruff]
select = ["E", "F", "W"]
fixable = ["ALL"]
exclude = [
    # TODO: Remove this in a follow-up where we fix __all__.
    ".tox",
    ".eggs",
    "ci/templates",
    "build",
    "dist",
    ".git",
    "__pycache__",
    "doc/conf.py",
    "doc/sphinxext",
    "__init__.py",
]
line-length = 80

[tool.ruff.per-file-ignores]
# "src/cucim/skimage/util/tests/test_shape.py" = ["E201", "E202"]

# [tool.black]
# line-length = 80
# target-version = ["py39"]
# include = '\.py?$'
# exclude = '''
# /(
#     thirdparty |
#     \.eggs |
#     \.git |
#     \.hg |
#     \.mypy_cache |
#     \.tox |
#     \.venv |
#     _build |
#     build |
#     dist |
# )/
# '''

[tool.setuptools]
license-files = ["LICENSE"]
